'use client';

import React from 'react';
import {
  Calendar,
  Cpu,
  FileText,
  Sparkles,
  ExternalLink,
  AlertCircle,
  Loader2,
  Zap,
  Clock,
} from 'lucide-react';
import type { DeepResearchResponse, ResearchErrorType } from '@/services/research';

interface ResearchResultsProps {
  query: string;
  data?: DeepResearchResponse | null;
  loading?: boolean;
  error?: string | null;
  errorType?: ResearchErrorType | null;
  retryAfter?: number | null;
}

function extractAbstract(text: string): string {
  const lines = text.split('\n');
  const paragraphs: string[] = [];
  for (const line of lines) {
    if (line.startsWith('## ') && paragraphs.length > 0) break;
    const clean = line.replace(/^##\s*Abstract\s*/i, '').trim();
    if (clean) paragraphs.push(clean);
  }
  return paragraphs.join(' ').slice(0, 600);
}

/** Inline: bold **text**, citation [1], links */
function renderInline(text: string, key: number): React.ReactNode {
  const parts = text.split(/(\*\*[^*]+\*\*|\[[^\]]+\]\([^)]+\))/g);
  return (
    <React.Fragment key={key}>
      {parts.map((part, i) => {
        if (/^\*\*[^*]+\*\*$/.test(part)) {
          return <strong key={i} className="font-black text-slate-800">{part.slice(2, -2)}</strong>;
        }
        const linkMatch = part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);
        if (linkMatch) {
          return <a key={i} href={linkMatch[2]} target="_blank" rel="noopener noreferrer" className="text-[#135bec] hover:underline font-medium">{linkMatch[1]}</a>;
        }
        return part;
      })}
    </React.Fragment>
  );
}

function MarkdownContent({ content }: { content: string }) {
  const lines = content.split('\n');
  const elements: React.ReactNode[] = [];
  let i = 0;
  let skipAbstract = false;

  while (i < lines.length) {
    const line = lines[i];

    // Skip the ## Abstract section entirely (already shown in callout box)
    if (line.match(/^##\s*Abstract\s*$/i)) {
      skipAbstract = true;
      i++;
      continue;
    }
    if (skipAbstract) {
      if (line.startsWith('## ')) {
        skipAbstract = false; // next section starts, stop skipping
      } else {
        i++;
        continue;
      }
    }

    if (line.startsWith('## ')) {
      elements.push(
        <h2 key={i} className="text-2xl font-black text-slate-900 tracking-tight mt-12 mb-4 pb-2 border-b border-slate-100">
          {line.slice(3)}
        </h2>
      );
    } else if (line.startsWith('### ')) {
      elements.push(
        <h3 key={i} className="text-lg font-black text-slate-800 mt-8 mb-3">{line.slice(4)}</h3>
      );
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      const items: string[] = [];
      while (i < lines.length && (lines[i].startsWith('- ') || lines[i].startsWith('* '))) {
        items.push(lines[i].slice(2));
        i++;
      }
      elements.push(
        <ul key={`ul-${i}`} className="space-y-2 mb-4 pl-2">
          {items.map((item, j) => (
            <li key={j} className="text-[14px] text-slate-600 leading-relaxed flex gap-2">
              <span className="text-[#135bec] mt-1.5 shrink-0 text-xs">•</span>
              <span>{renderInline(item, j)}</span>
            </li>
          ))}
        </ul>
      );
      continue;
    } else if (line.trim() !== '') {
      elements.push(
        <p key={i} className="text-[14px] text-slate-600 leading-relaxed mb-4">
          {renderInline(line, i)}
        </p>
      );
    }

    i++;
  }

  return <>{elements}</>;
}

export default function ResearchResults({
  query, data, loading, error, errorType, retryAfter,
}: ResearchResultsProps) {
  const abstract = data ? extractAbstract(data.answer) : '';

  return (
    <div className="min-h-[calc(100vh-60px)] bg-white border-t border-slate-100">
      <main className="w-full bg-white">
        <div className="max-w-[900px] mx-auto p-12 lg:p-20 space-y-10 animate-in fade-in slide-in-from-bottom-4 duration-700">

          <div className="flex items-center gap-2 text-[#135bec]">
            <Sparkles size={14} className="fill-[#135bec]" />
            <span className="text-[10px] font-black uppercase tracking-[0.2em]">Deep Research Output</span>
          </div>

          <div className="space-y-4">
            <h1 className="text-4xl lg:text-5xl font-black text-slate-900 leading-[1.1] tracking-tight">{query}</h1>
            <div className="flex flex-wrap items-center gap-6 text-[11px] font-bold text-slate-400">
              <span className="flex items-center gap-2">
                <Calendar size={14} />
                {new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
              </span>
              <span className="flex items-center gap-2"><Cpu size={14} />Generated by DeepScholar AI</span>
              {data && (
                <span className="flex items-center gap-2">
                  <FileText size={14} />
                  Confidence: {Math.round(data.confidence_score * 100)}% · {data.iterations_used} iteration{data.iterations_used !== 1 ? 's' : ''}
                </span>
              )}
            </div>
          </div>

          {/* Loading */}
          {loading && (
            <div className="flex flex-col items-center justify-center py-32 gap-6">
              <Loader2 size={40} className="text-[#135bec] animate-spin" />
              <div className="text-center space-y-2">
                <p className="text-sm font-black text-slate-700">Running agentic pipeline...</p>
                <p className="text-xs text-slate-400">Planner → Researcher → Writer → Reviewer</p>
              </div>
            </div>
          )}

          {/* Error */}
          {error && !loading && (
            errorType === 'rate_limit' ? (
              <div className="flex flex-col items-center justify-center py-24 gap-6 text-center">
                <div className="w-20 h-20 rounded-full bg-amber-50 border-2 border-amber-100 flex items-center justify-center">
                  <Zap size={32} className="text-amber-400" />
                </div>
                <div className="space-y-2 max-w-sm">
                  <p className="text-xl font-black text-slate-800">AI đang quá tải</p>
                  <p className="text-sm font-medium text-slate-500 leading-relaxed">
                    Hệ thống đã dùng hết lượt token cho phép trong phút này. Vui lòng đợi một chút rồi thử lại.
                  </p>
                  {retryAfter && (
                    <p className="text-xs font-bold text-amber-500 flex items-center justify-center gap-1.5 pt-1">
                      <Clock size={12} />Thử lại sau khoảng {retryAfter} giây
                    </p>
                  )}
                </div>
              </div>
            ) : (
              <div className="flex items-start gap-4 p-6 rounded-2xl bg-red-50 border border-red-100">
                <AlertCircle size={20} className="text-red-500 shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <p className="text-sm font-black text-red-700">
                    {errorType === 'network' ? 'Không thể kết nối đến AI service' : 'Đã xảy ra lỗi'}
                  </p>
                  <p className="text-xs text-red-500 leading-relaxed">{error}</p>
                </div>
              </div>
            )
          )}

          {/* Results */}
          {data && !loading && (
            <>
              {abstract && (
                <div className="bg-white rounded-3xl p-10 border-2 border-slate-50 shadow-2xl shadow-slate-200/40 relative">
                  <div className="absolute top-10 left-10 text-[11px] font-black uppercase tracking-[0.2em] text-[#135bec] opacity-50">
                    Abstract
                  </div>
                  <p className="pt-8 text-lg font-medium text-slate-600 leading-relaxed italic">{abstract}</p>
                </div>
              )}

              <div>
                <MarkdownContent content={data.answer} />
              </div>

              {/* Sources at bottom */}
              {data.sources && data.sources.length > 0 && (
                <div className="border-t border-slate-100 pt-10 pb-20 space-y-4">
                  <h3 className="text-[11px] font-black uppercase tracking-[0.2em] text-slate-400">
                    Sources ({data.sources.length})
                  </h3>
                  <div className="grid gap-2 sm:grid-cols-2">
                    {data.sources.map((s) => (
                      <a
                        key={s.index}
                        href={s.url || '#'}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="flex items-start gap-3 p-3 rounded-xl border border-slate-100 hover:border-[#135bec]/20 hover:bg-blue-50/40 transition-all group"
                      >
                        <span className="text-[10px] font-black text-[#135bec]/50 mt-0.5 shrink-0 w-6">[{s.index}]</span>
                        <span className="flex-1 text-[12px] font-medium text-slate-600 group-hover:text-slate-900 leading-snug line-clamp-2">{s.title}</span>
                        {s.url && (
                          <ExternalLink size={12} className="shrink-0 mt-0.5 text-slate-300 group-hover:text-[#135bec] transition-colors" />
                        )}
                      </a>
                    ))}
                  </div>
                </div>
              )}
            </>
          )}

        </div>
      </main>
    </div>
  );
}
