services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: deepscholar-frontend
    environment:
      - NEXT_PUBLIC_AI_URL=http://localhost:8001/api
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - NEXT_PUBLIC_FACEBOOK_APP_ID=${NEXT_PUBLIC_FACEBOOK_APP_ID}
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=300
    volumes:
      - .:/app
      - deepscholar_node_modules:/app/node_modules
      - /app/.next
    ports:
      - "3000:3000"

volumes:
  deepscholar_node_modules:
